### ISSUE TITLE
Feature request: windows native symbolic link

### ISSUE THREAD

**Issue by QiangF** [anishathalye/dotbot#102]
Hello everyone,
I am using dotbot in cygwin. The link created by dotbot doesn't work for some programs, it is of this format:

    !<symlink ? home/.bashrc

The native command to create symlink is mklink in windows. How do I use it to create the symlinks?
Thank you!

**Comment by nagromc** [comment]
Indeed, the symlinks created by Cygwin are not compatible with Windows itself. I mean, in your Cygwin terminal, you can follow a symlink:

```shell
$ # in your Cygwin terminal emulator
$
$ echo "foo" > bar.txt
$ ln -s bar.txt baz
$ cat baz
foo
$
```

So, it does work in a Unix environment (here, Cygwin).

But if you try to open that symlink in Windows, you will display the symlink itself and not its target.

```shell
> # in a cmd.exe Windows command-line interpreter
>
> # cd to the directory where bar.txt and baz have been previously created
> dir
# some information about volume and current directory
10/11/2016  13:19                 4 bar.txt
> # `baz` is not listed. Right click > Properties on `baz` shows it is a system file
> more bar.txt
foo
> more baz
!<symlink> ■b
a
r
.
t
x
t
```

I stumbled upon this issue months ago, but I couldn't find a solution. I think it is related to Cygwin, and not to Dotbot though.

**Comment by QiangF** [comment]
Maybe use link shell extension to create the symlink.
http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html

**Comment by karlding** [comment]
What is the intended behaviour for this on Windows? Is the idea that running dotbot under any Windows environment will use the ``mklink`` command (and create a symbolic link), regardless of whether it's run in Cygwin/Git Bash/cmd.exe/PowerShell/whatever?

I believe you can call the ``CreateSymbolicLink`` [API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363866(v=vs.85).aspx), and do something like

```python
import ctypes

kdll = ctypes.windll.LoadLibrary("kernel32.dll")
# file
kdll.CreateSymbolicLinkW(UR"D:\target_file.txt", UR"D:\source_file.txt", 0)
# directory
kdll.CreateSymbolicLinkW(UR"D:\target_dir", UR"D:\source_dir", 1)
```

This would require Windows Vista and up.

**Comment by nagromc** [comment]
I just [stumbled upon a Cygwin feature](https://github.com/agross/dotfiles/blob/025f4710816f6870968dc2a91402bed1e8a504eb/README.markdown#cygwin). I haven't tried, but it seems you can set the `CYGWIN` environment variable to use Windows shortcuts instead of regular symlinks:

```
$ CYGWIN=winsymlinks:nativestrict
$ ./install
```

Maybe a good alternative before the issue is resolved.

Moar docs: [here](https://cygwin.com/cygwin-ug-net/using.html#pathnames-symlinks) and [here](https://cygwin.com/cygwin-ug-net/using-cygwinenv.html).

**Comment by flickerfly** [comment]
Wow, oldie request, but sure would be nice. :-)

**Comment by anishathalye** [comment]
As someone who doesn't use Windows regularly, I don't understand the Windows filesystem and the ecosystem of Cygwin/similar apps and the interaction between that and WSL well enough, but if someone submits a PR that improves symlinking behavior on Windows, I would be happy to accept it.

**Comment by flickerfly** [comment]
I found that I need to run it with Administrative rights to have permissions to create the links, but the next run says the link is wrong which I assume is related to an unexpected way the filesystem presents the link.

**Comment by daephx** [comment]
I've been toying around with this recently and have tried out some things id like to share:

Since the windows 10 creator update, 
if you enable `Developer mode` you can then create symbolic links without administrator privilege!
Since git's config is rather consistent between windows and Linux I tested that: `$HOME` || `$HOME/.config/git`
And it managed to create the links.

Though as @flickerfly said, on second run:
`Incorrect link ~/.config/git\aliases -> \\?\C:\Users\$USER\.dotfiles\dotfiles\git\aliases`
The output can be mitigated by adding `force` to the link directive but doesn't inspire confidence.

ANSI colors also were not working out of the box on my windows machine,

```plain
?[95mLinking failed ~/.config/git\config -> C:\Users\$USER\.dotfiles\dotfiles/git\config?[0m
?[91mSome links were not successfully set up?[0m
?[94msudo: begin subprocess?[0m
```

so I found a hack by injecting a small plugin:

`bin/dotbot -p ./meta/plugins/windows/windows.py`

```py
import ctypes

if os.name != "nt":
    raise OSError("Current plugin only supports nt/windows systems")

# The magic!
kernel32 = ctypes.windll.kernel32
kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
```

While playing around with UAC and self-elevation before learning about developer mode I did get the sudo plugin to work by making sure `bin/dotbot` was called using python and using the windows utility `gsudo` alias: `sudo` to mimic Linux.
But I had some issues with double runs. I just still haven't gotten `ctype` w/ `runas` or `subprocess` to create the links.

Since the main shell on windows is PowerShell, 
I modified my install script to run as both valid bash and pwsh attempting to have a single Entrypoint for installing.
References:
- https://github.com/chrisfcarroll/PowerShell-Bash-Dual-Script-Templates
- https://stackoverflow.com/questions/39421131/is-it-possible-to-write-one-script-that-runs-in-bash-shell-and-powershell/67292076#67292076

Assuming any of this manages to work out I feel as though windows / pwsh configs will have to be explicitly separate from Linux / bash ones ala `github.win.yaml` or `github.pwsh.yaml` depending. because shelling out from pwsh to a config that has bash conditions will probably error.
