### ISSUE TITLE
$USER variable not correct

### ISSUE THREAD

**Issue by QiangF** [anishathalye/dotbot#115]
content of sudo.install:

    #!/usr/bin/env bash
    set -e
    export PATH=/my_bin/anaconda2/bin:$PATH
    CONFIG="sudo.install.conf.yaml"
    DOTBOT_DIR="dotbot"
    DOTBOT_BIN="bin/dotbot"
    BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    cd "${BASEDIR}"
    (cd "${DOTBOT_DIR}")
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

content of sudo.install.conf.yaml:

    - defaults:
        link:
        relink: true
        create: true

    - clean: ['~']

    - link:
        /etc/systemd/system/suspend.target.wants/slock@$USER.service: etc/systemd/user/slock@.service

commands executed:

    sudo -E ~/.dotfiles/sudo.install

created symlink name:

        /etc/systemd/system/suspend.target.wants/slock@$root.service

Why the $USER variable is substituted with root?

**Comment by dein0s** [comment]
That's because of how ```sudo -E``` works. It preserve env vars only for the current command executed.
Just check the output of ```sudo -E env``` to see what the actual variables are.

For this particular case you can use ```${SUDO_USER}``` in your config to set the propper value. However, it may sometimes fail because of missing variable. And as dotbot currently use the default emplementation of [os.path.expandvars](https://docs.python.org/2/library/os.path.html#os.path.expandvars), you can't set a substitution like this ```${SUDO_USER:-${USER}}``` in your config file. Check #56 for more info.

**Comment by QiangF** [comment]
$SUDO_USER works! This is the changed line in sudo.install.conf.yaml:

    /etc/systemd/system/suspend.target.wants/slock@$SUDO_USER.service: etc/systemd/user/slock@.service

Also $HOME expands correctly to the user' home, eg. another link in sudo.install.conf.yaml

    /etc/hosts: $HOME/Nutstore/dotfiles/hosts

**Comment by dein0s** [comment]
> Also $HOME expands correctly to the user' home, eg. another link in sudo.install.conf.yaml

That's because executing ```sudo <command>``` doesn't overrides ```$HOME```
Again, you can check ```sudo -E env``` to see the list of all actual env variables that you can access.
