### ISSUE TITLE
Shell command conflict with yaml syntax

### ISSUE THREAD

**Issue by QiangF** [anishathalye/dotbot#123]
In install.conf.yaml

    - shell:
    - [ bash -c "[[ -d ~/temp ]] || mkdir ~/temp", create temp directory]

The error is 

    expected ',' or ']', but got '['

**Comment by arcticicestudio** [comment]
There is no need to explicitly call `bash -c` since dotbot will use the $SHELL of the current user.
To fix the `[` and `|` character parser error you need to use a single-quotes scalar which will automatically escape these characters [as documented in the YAML specification](http://yaml.org/spec/current.html#id2534365).

I've tested this config and it works fine:
```yml
- shell:
  - [ '[[ -d ~/temp ]] || mkdir ~/temp', crete temp directory]
```
