### ISSUE TITLE
Force should noop if the files are identical

### ISSUE THREAD

**Issue by x89** [anishathalye/dotbot#133]
I think when forcing the recreation of files if you've said to force recreate them yet they match identically then the file shouldn't be overwritten.

This would stop edge case bugs where a config's change is picked up during the remove/creation process and the program bugs out. It would also involve less filesystem changes.

It should be quite a simple change in one location with the use of `filecmp.cmp`.

**Comment by anishathalye** [comment]
Hmm, I'm actually not sure about this. I think if you have a file in your dotfiles repository `~/src/dotfiles/foo` and a **copy** of that file in `~/foo`, then it should be overwritten with a symlink. Otherwise, if you edit `~/foo`, you won't notice that if you run a `git status`, and if you subsequently run a `./install`, then your changes will be destroyed by the old copy. I think having a symbolic link all the time helps avoid this confusion.

**Comment by anishathalye** [comment]
Closing because this is intentional. If there's anything new, feel free to reopen.
