### ISSUE TITLE
Contribution Request: Another small plugin for core (details inside)

### ISSUE THREAD

**Issue by dsifford** [anishathalye/dotbot#149]
Hello again, @anishathalye :wave: 

I recently finished up a small plugin locally for my own use and it's pretty darn useful for a particular use-case that I think might also be useful for a large portion of other users.

This issue is just to gauge your interest in adding it into core (after a thorough code review, of course).

### The gist

The plugin is called `merge`, and it is used like this (subject to changes):

```yml
- merge:
    ~/dest: source
```

As you can see, it works very much like `link`, however, the difference is that instead of linking `dest` to `source`, it "merges" the contents of `source` into `dest` (with symlinks `dest -> src`).

The salient use-case for this is with dotfiles belonging in the `$XDG_CONFIG_HOME` or `~/.config` directory.

Instead of having to do this:

```yml
- link:
    ~/.config/foo: config/foo
    ~/.config/bar: config/bar
    ~/.config/baz: config/baz
```

You instead only have to do this:

```yml
- merge:
    ~/.config: config
```

Ah, much better :smile:

Anyway, I just finished a decent working implementation last night for my own personal use that so far works nicely for my needs. 

Let me know if you might be interested in a PR for this. If not, no hard feelings. :+1:

**Comment by dsifford** [comment]
Forgot to mention: A question might be "why not just 'link' `~/.config` to `config`, or `dest` to `src`?"

The answer to that is simply that sometimes users do not want to keep the entire contents of `dest` in version control. That's definitely the case of the `~/.config` directory.

**Comment by anishathalye** [comment]
Oh neat! Just wondering, does globbing (#142) already cover this use case?

**Comment by dsifford** [comment]
Hm, didn't notice that.

Quickly looking at it, I suppose it does, but it looks like it could be quite dangerous to use, no? Because a malformed glob could potentially create deeply nested symbolic links which, if removed from source, would be pretty challenging to clean up in dest.

The implementation I have is largely inspired by your link implementation (even using the same error messages in the same spots), and much safer in that it guarantees links only happen one directory below the source.

That last part is nice because it makes the situation super easy to keep clean and free of dead links.

Example:

```yml
- clean: [ '~/.config', '~/foo', '~/bar' ]

- merge:
    ~/.config: config
    ~/foo: foo
    ~/bar: bar
```

To be honest, I don't think I'd be comfortable using globbing and would probably still use my little merge implementation once that merges for that reason.

Thoughts? Am I misreading something in the globbing PR?

**Comment by dsifford** [comment]
Finally got around to pushing the plugin to github..

[Here's a link](https://github.com/dsifford/.dotfiles/blob/master/.lib/plugins/merge.py) if you're interested in checking it out... I run it several times in my configuration and it's working pretty well for me.

**Comment by robobenklein** [comment]
I guess 'glob' in this case is ambiguous, there's no recursion in the globbing routine, it simply looks at all the files matching the wildcard and treats them as individual links into dest.

You said:
```
- merge:
    ~/.config: config
```

But would this do what you wanted?
```
- link:
    ~/.config/:
      glob: true
      path: config/*
```
(all items directly in config are linked with their same name to ~/.config, regardless if they are a folder or file)

Example: https://github.com/robobenklein/configs/blob/afb9f1a921931914338e982c9dcc5ff115f7cb4c/install.conf.yaml#L7

I can have other files in my ~/bin and anything from bin/* will get linked there, folders included, without any recursion into deeper levels.

**Comment by dsifford** [comment]
I see. Thanks for clarifying.

So if there is no globbing beyond a single level deep whatsoever, would it make more sense to use your implementation and just call it merge? 

Or am I misunderstanding? Is the globbing happening in source, but not dest? The ambiguity here is what concerns me the most and makes me nervous to try it.

I think there's merit in separating single links and "glob" or "merge" links because the distinction between them is something that should be deliberate.

PS: That `linkif` conditional linking you've got there looks pretty :ok_hand: :ok_hand:

**Comment by robobenklein** [comment]
Do you have docker?

If so, and you want to learn how the globbing works, you could run my docker container that I build from my configs repo: https://hub.docker.com/r/robobenklein/home/

I use it all the time for trying out changes which I might expect to break my repos or when I'm experimenting with zsh settings, etc.

Run the `./install -v` to be verbose, it will show all the matched globs that it finds.

Here's an excerpt from what my config looks like when using `./install -v`:

```
Globbing with path: bin/*
Globs from 'bin/*': ['bin/cpu_clock.sh', 'bin/conky-convert.lua', 'bin/whosonhydra', 'bin/scan-wifi.sh', 'bin/rtab']
Link exists ~/bin/cpu_clock.sh -> /home/robo/code/configs/bin/cpu_clock.sh
Link exists ~/bin/conky-convert.lua -> /home/robo/code/configs/bin/conky-convert.lua
Link exists ~/bin/whosonhydra -> /home/robo/code/configs/bin/whosonhydra
Link exists ~/bin/scan-wifi.sh -> /home/robo/code/configs/bin/scan-wifi.sh
Link exists ~/bin/rtab -> /home/robo/code/configs/bin/rtab
```

The reason I didn't originally call it "merge" was because the original intent was just to create a number of individual link operations for a set of files (using a `*` which I would normally call a glob operator or wildcard), instead of the viewpoint of saying "merge these two folders by symlinking files in them". (Also we are using the python glob module, which shares the naming convention...)

**Comment by dsifford** [comment]
Thanks for the resources. Yep, familiar with docker and globbing believe it or not :stuck_out_tongue_closed_eyes: 

I get what you're saying (I think)... I just want to confirm that the implementation wont allow for things like this to happen....

```yml
- link:
    ~/.config:
      path: config/**/*.txt
      glob: true
```

And the reason why that is worrisome for me is because it would be super annoying to clean up if someone did that mistakenly and created nested links inside `~/.config`.

And if that's not in fact the case, and the entire use case is just merging the contents of one directory into another, why depend on the `glob` module at all? The one I'm using doesn't and it seems to work fine with everything I'm throwing at it.

**Comment by robobenklein** [comment]
Ah, there you have shown the missing point in Python's glob module - there's no double-`*` operator, they behave as a normal single `*`.

The reason I wanted a glob instead of a merge is also somewhat described in your example.

Say for example I'm managing my tmux configs in a version-specific manner, and I only wanted to merge the .conf files that were two levels deep?

```yaml
- link:
    ~/.config/tmux/:
      path: tmux/*/*.conf
      glob: true
```
Which is actually almost what I'm doing anyways...
```
tmux
├── 1.9
│   ├── keybinds-vi.conf -> ../keybinds-vi.conf
│   ├── mouse-mode-old.conf -> ../mouse-mode-old.conf
│   └── powerline-py3-old.conf -> ../powerline-py3-old.conf
├── 2.1
│   ├── bind-pane-zoom.conf -> ../bind-pane-zoom.conf
│   ├── keybinds-vi.conf -> ../keybinds-vi.conf
│   ├── mouse-mode-new.conf -> ../mouse-mode-new.conf
│   └── powerline-py3.conf -> ../powerline-py3.conf
```
If I didn't have a tmux version switcher in my `.tmux.conf` then I'd have to use the globs there combined with my `linkif` in order to correctly do version-dependant things like that.

In a repo I don't currently have public, I have a similar setup but with non-`.conf` files mixed in, and varying depths of directories. (I've been using dotbot for a lot more than just bootstrapping dotfiles at this point...)

**Comment by robobenklein** [comment]
You brought up a very good point about the clean plugin I hadn't considered... I'm not really sure what I'm going to do about it, but I now realize there might be an implementation bug waiting there lol...

As far as I know, the clean plugin should still work since it's [cleaning all the items in the target dir](https://github.com/anishathalye/dotbot/blob/a517c4c5d0b6bdd8ab3a62f3c6c3f38837354bde/plugins/clean.py#L37), but in the case of linking a nested or multi-level deep folder I'm not sure of the cleaning behaviour yet...

If I were to rename the 1.9 folder for example, I'd probably be left with symlinks that dotbot had zero clue that it was even supposed to be managing, since the destination is now dependant on the source naming convention as well... (but I could easily fix this problem by just adding a glob reference in the linkif plugin, `linkif: path: tmux/*, if: 'test -f tmux/${glob}/*.conf'` or something)

I haven't yet seen any problems or instances in which it's been a problem, but I think I could imagine a use case where it might. (Albeit I'm not sure that there's anybody really using that use case right now...)

**Comment by dsifford** [comment]
Looks like you guys went with globbing. Closing this as irrelevant.
