### ISSUE TITLE
Option to uninstall/clean files?

### ISSUE THREAD

**Issue by ghost** [anishathalye/dotbot#152]
In a scenario where someone wants to completely remove all dotfiles and their symlinks, what do they have to do? Simply deleting the directory leads to numerous dead links.

**Comment by micarlise** [comment]
:+1: for the ability to uninstall.  

Some simple python can read your config file and remove all symlinks.  You can put this as a uninstall.py in your dotfiles.

```
#!/usr/bin/env python

from __future__ import print_function

import yaml
import os

CONFIG="install.conf.yaml"

stream = open(CONFIG, "r")
conf = yaml.load(stream)

for section in conf:
    if 'link' in section:
        for target in section['link']:
            realpath = os.path.expanduser(target)
            if os.path.islink(realpath):
                print("Removing ", realpath)
                os.unlink(realpath)
```

**Comment by anishathalye** [comment]
If/until there's native support for this, the script above might be nice to put in the [wiki](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks).

**Comment by dagadbm** [comment]
done

**Comment by anishathalye** [comment]
Thanks!

**Comment by daveyarwood** [comment]
I was able to get the code above to work just now in macOS Sonoma. Here's my slightly modified version of the script, in case it's helpful to others:

```python
#!/usr/bin/env python3

from __future__ import print_function

import yaml
import os

CONFIG="install.conf.yaml"

stream = open(CONFIG, "r")
conf = yaml.load(stream, Loader=yaml.CLoader)

for section in conf:
    if 'link' in section:
        for target in section['link']:
            realpath = os.path.expanduser(target)
            if os.path.islink(realpath):
                print("Removing ", realpath)
                os.unlink(realpath)
```

At first, it complained that it couldn't find the `yaml` module, but that was easily fixed by running `pip3 install pyyaml`.

Things I changed in the script:

* Changed `python` to `python3` in the shebang line.
* Added `Loader=yaml.CLoader` argument to `yaml.load` call.

I used this to successfully uninstall all my symlinks so that I could move my dotfiles folder and then reinstall the symlinks.
