### ISSUE TITLE
PyPI package is broken

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#161]
See https://github.com/anishathalye/dotbot/pull/160#issuecomment-394047536

cc @dsifford

**Comment by dsifford** [comment]
Maybe Ranger's setup.py might be able to shed some insight on something this package has missing:

https://github.com/ranger/ranger/blob/master/setup.py

**Comment by anishathalye** [comment]
welp, fixing this has been quite the adventure. I tested by making the wheel, copying to a fresh environment, and running `dotbot --help` to make sure that it works. I didn't actually try running on a configuration, so I didn't notice that the built-in plugins were missing.

hopefully this is fixed in #165

**Comment by dsifford** [comment]
Haha no worries, I appreciate all the work you've done and continue to do on this. (I know I've been next to useless!).

If you just push out a release to PyPI, I'll pull it over and test from there if that would be helpful. Otherwise, I'll wait for the other guy you tagged in the PR thread to look it over since I'm not super familiar with PyPI packaging.

**Comment by dsifford** [comment]
Well shoot, that was easy... Yep, looks like it's working fine now. :+1:
