### ISSUE TITLE
Feature request: support !!omap in YAML configs

### ISSUE THREAD

**Issue by jkeroes** [anishathalye/dotbot#166]
An ordered map would make, for example, the `relink` hash tables execute in order, which would present clearer output. It would also help when reviewing the output log to see what was was, when, and what may have been missed.

The YAML syntax looks basically like this:
```
- relink !!omap
    - ~/.foo: "foorc"
    - ~/.bar: "bar_file"
    - ~/.baz:
```

I believe support would need to be added in config.py.

As an aside, this would likely be a YAML-only feature. There doesn't appear to be support provided by the default JSON parsers.

**Comment by anishathalye** [comment]
Good idea!

It would be nice to support this for both JSON and YAML, do it by default, and not have any syntactic overhead in the configuration files.

It looks like this is possible [[1](https://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts), [2](https://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict)]. And it looks like with Python 3.7+ and PyYAML, order is preserved by default [[3](https://github.com/yaml/pyyaml/issues/110), [4](https://www.python.org/downloads/release/python-370/)]. We should be able to find some clean solution that works across the Python versions supported by Dotbot (

If anyone wants to work on this, I'm happy to review a PR, otherwise I'll get around to implementing this sometime soon.

**Comment by anishathalye** [comment]
On second thought: I don't think it's worth the additional complexity involved in implementing this functionality in a backward-compatible way. Especially since I think people shouldn't rely on this behavior for correctness, only for readability of the output, so it's not critical if it doesn't work on some platforms.

Even though Dotbot will continue to support Python 2.7 and Python 3.4+ for the foreseeable future, Python 2 has been [sunset](https://pythonclock.org/), and PyYAML on Python 3.7+ already has this behavior of preserving order.
