### ISSUE TITLE
Track master branch in submodule and ignore dirty commits

### ISSUE THREAD

**Issue by darsh12** [anishathalye/dotbot#191]
Hi,
So i found out that when dotbot is added as a submodule, it automatically detaches itself from the head, practically having its own branch. After much research i found that providing ` -b <branch>` automatically tracks the submodule brach, making it `git submodule add -b master https://github.com/anishathalye/dotbot`.

Another issue I was having, was that whenever i ran dotbot it automatically created a *dirty* commit in the dotbot submodule. This is also preventable by adding ` ignore = dirty ` in the `.gitmodules` file under respective submodule. 

This solves issues when trying to automate dotfiles provisioning with ansible, in my case. 

Could the README be updated with this information?

**Comment by anishathalye** [comment]
(comments on `-b master` in #192)

re: `ignore = dirty`, maybe that would be nice to add to the instructions. I think it's only `.pyc` files, and I'm guessing most people don't notice it because of a `*.pyc` rule in their global `.gitignore`. Can the `ignore = dirty` flag be set via a command line option or something? It's a little annoying to include a "edit this file in this way" in the otherwise small/simple sequence of instructions for adding Dotbot to a git repo.

**Comment by darsh12** [comment]
Yep, found the command line option

`git config -f .gitmodules submodule.dotbot.ignore dirty`. This should automatically add the `ignore = dirty` under the dotbot submodule

**Comment by anishathalye** [comment]
Ooh that is awesome, I didn’t know you could do that! Could you submit a separate PR that makes that change (add the line following the `submodule add` line?)

**Comment by anishathalye** [comment]
Resolved via #194. Thanks!
