### ISSUE TITLE
'If' examples. 

### ISSUE THREAD

**Issue by jdehnert** [anishathalye/dotbot#206]
Thanks for the feedback.  I thought the least I could do is to show you what I was doing (wrong) in my config file.  Most of the entries are pretty straight forward, but I had these two entries that I was having problems with.

```
# Mac config files
- link:
    ~/.osx:              mac/osx
    if: "[ ${OSTYPE} =~ ^darwin ]"
    ~/.brew:             mac/brew
    if: "[ ${OSTYPE} =~ ^darwin ]"
```

so if I understand the example you added correctly what I should be doing is...

```
- link:
    ~/.osx:
    if: "[ ${OSTYPE} =~ ^darwin ]"
    path: mac/osx
```

Separating the target and the link on different lines was non-intuitive to me.  My brain went right to 

```
Link This to That
IF something is true
```

I personally think it would be ideal you were able to create a bash style block so one could add a number of links inside of it.   Something like...

```
- link:
  if: "[ ${OSTYPE} =~ ^darwin ]" ; then
    ~/.brew:             mac/brew
    ~/.osx:              mac/osx
  ...etc.
  fi
```
or perhaps just
```
- link:
  if: "[ ${OSTYPE} =~ ^darwin ]"
    ~/.brew:             mac/brew
    ~/.osx:              mac/osx

- link: 
    ~/.aliases:          bash/aliases
    ~/.bash_profile:     bash/bash_profile
```
where the following link, or any statement that's back at the margin,  escapes out of the IF statement above it.

But I'm not going to ask for any such drastic changes.  I appreciate what you have made available, and now that I understand it better I should be fine.

**Comment by anishathalye** [comment]
Ah I see, thanks for sharing! Yeah, I agree that the syntax is a little unintuitive -- it doesn't look like a programming language. I guess that's one of the disadvantage of having YAML files that are not just representing data, and are essentially interpreted as programs, rather than writing a proper custom DSL.

I think your example syntaxes look neat, but sadly, they don't fit into YAML syntax, so something like that wouldn't be doable without a backwards-incompatible change.

I'm kinda tempted to try reimplementing Dotbot as an embedded DSL rather than using YAML config files. Python isn't the greatest host language for this, but it would be interesting to try. Doing it as an embedded DSL in Racket also seems like it would be really neat (probably undesirable for deployability reasons, but could be cool to try regardless).

**Comment by anishathalye** [comment]
Going to close this issue since I don't think there's anything we can do right now (maintaining compatibility with the current YAML syntax, etc).
