### ISSUE TITLE
Handling PATH updates

### ISSUE THREAD

**Issue by jamesstidard** [anishathalye/dotbot#207]
Hi,

In one of my dotfile configurations, I install the cli `asdf` and I also use the dotbot plugin [dotbot-asdf](https://github.com/sobolevn/dotbot-asdf) to then configure things. However, when I first run my `install.sh` it will always fail, as the `asdf` is not available on the `PATH`. This normally means for me: restarting a terminal session and rerunning the `install.sh` so the plugin can see the updated `PATH`.

I tried to fix this by exporting a expanded `PATH` using the shell options on the line before the plugin config, but this didn't seem to work. i.e. 

```
- shell:
  - export PATH="/path/to/asdf/bin:$PATH"

- asdf:
  ...
```

Is there a way to achieve this, so the plugin can see the install. Or is this something that the plugin would need to support - like accepting a `bin` path option?

Thanks for any help.

**Comment by anishathalye** [comment]
So the `shell: export PATH="..."` is not going to work, because those commands are run in a subprocess, and so whatever happens there won't affect the Dotbot process.

If you want to change environment variables when running Dotbot itself, one way you can do it is by modifying the [install](https://github.com/anishathalye/dotbot/blob/master/tools/git-submodule/install) file, adding something like `PATH="/path/to/asdf/bin:$PATH"` anywhere before the last line that calls Dotbot.

**Comment by jamesstidard** [comment]
Ah yes, thanks @anishathalye. I'll give that a shot.

Thanks again.
