### ISSUE TITLE
[Question] Tracking binaries

### ISSUE THREAD

**Issue by yutaizhou** [anishathalye/dotbot#218]
Hi! Excellent work with this, I love how easy and flexible it is to edit, track, and install my dotfile repo. The Missing Semester course and your personal dotfile repo have been absolutely wonderful to learn from. (especially the way you structure your bashrc)

What is the best practice for tracking personal executable? For example, I would like to have `$HOME/bin/broot` installed and `$HOME/bin` added to path for every machine I use. Tracking binaries w/ git is not a good idea. What is the recommend approach?

Thank you!

**Comment by anishathalye** [comment]
Where does `broot` come from? Is it e.g. a C program that you've written, that needs to be compiled and installed on each machine?

**Comment by yutaizhou** [comment]
No it is simple a package that I downloaded from [here](https://dystroy.org/broot/install/)

I learned about it from [this Missing Semester lecture](https://missing.csail.mit.edu/2020/shell-tools/)

**Comment by anishathalye** [comment]
I see. I generally install packages using a package manager (Homebrew on macOS, apt on Linux), and this is not tracked in my dotfiles. Some people track a list of installed applications (e.g. with a [Brewfile](https://thoughtbot.com/blog/brewfile-a-gemfile-but-for-homebrew)) in their dotfiles.

**Comment by yutaizhou** [comment]
Is there any reason why you don't track your installed applications?  A lot of the cool applications mentioned in that course like Broot, [bat](https://github.com/sharkdp/bat), [fzf](https://github.com/junegunn/fzf) all requires separate installation once you move to a new machine.

**Comment by anishathalye** [comment]
Ah I just don't track it in my dotfiles, I have a separate repo where I have a list of my applications, so when I set up a new machine, I can install them easily. E.g. https://github.com/anishathalye/linux-bootstrap for my linux machines. It's not fully automated, but it's close enough, and I do this rarely enough that it's probably [not worth improving](https://xkcd.com/1205/). When I did have a more specific use case, e.g. provisioning GPU machines for deep learning, I wrote a script that fully [automates](https://github.com/labsix/scripts/blob/master/provision-gpu-box.bash) the process.

Also, I have a slightly different scheme for tracking apps for my desktop machine, because it's a macOS machine where some of the applications have to be installed manually (and aren't available e.g. in `brew cask`). There, I just have a Markdown file that lists everything I have installed, also tracked via Git in my personal wiki.

Also, for the way I use my computers, tracking _which_ applications installed isn't super critical. Usually, my machines end up having slightly different sets of software installed. In the worst case, if I miss something, I'll notice it when I try to run the command, and then I can go and install it. But I do like tracking my _configuration_ of all these applications in my [dotfiles](https://github.com/anishathalye/dotfiles) / [dotfiles-local](https://github.com/anishathalye/dotfiles-local), because the version history is helpful, and also the configuration would be too much work to recreate.

**Comment by yutaizhou** [comment]
This makes sense, thank you for the great explanation! Always cool to see how more experienced people like you manage their setups. :)
