### ISSUE TITLE
Unable to update link for directory

### ISSUE THREAD

**Issue by dietofworms** [anishathalye/dotbot#228]
### Issue
I can't update the dotbot repository to reflect local changes

### Explanation
I initialised my dotfiles repo using the `init_dotfiles.sh` example. It worked fine but it skipped my `~/.newsboat` directory. I went into the code for the `init_dotfiles.sh` and added a line to check for my newsboat folder. That worked fine and I commited and pushed the changes to github. The issue is that now I have made changes to my newsboat config files and I cannot run `./install` to update the links. I receive the following error: 
```
.dotfiles ±|master ✗|$ ./install
All targets have been cleaned
Link exists ~/.bash_profile -> /home/skarm/.dotfiles/bash_profile
Link exists ~/.bashrc -> /home/skarm/.dotfiles/bashrc
Link exists ~/.bash_logout -> /home/skarm/.dotfiles/bash_logout
Link exists ~/.gitconfig -> /home/skarm/.dotfiles/gitconfig
Link exists ~/.vimrc -> /home/skarm/.dotfiles/vimrc
Link exists ~/.config/openbox -> /home/skarm/.dotfiles/config/openbox/
~/.newsboat already exists but is a regular file or directory
Some links were not successfully set up

==> Some tasks were not executed successfully
```

### Extra
It is worth noting that the `.newsboat` directory was a git repo however I tried removing the `.git` folder and it still didn't work.

**Comment by dietofworms** [comment]
I found the solution so I'll leave it here.

### Solution
- Delete the existing repository in the `$HOME` directory
- Run `install.sh` again (since I had already set it up once with the initial run)

Should I be running `install.sh` everytime I make a change to a config file?

**Comment by anishathalye** [comment]
Glad you got it working.

Yes, Dotbot requires that the original file/folder doesn't exist, so it can create a symlink. If you want Dotbot to automatically delete the file/folder when relevant, you can use the `force: true` option (though I personally prefer not to use this).

You don't need to run `install.sh` every time you make changes to a config file, because they're [symlinked](https://en.wikipedia.org/wiki/Symbolic_link) into place (not copied), so the changes can be "seen" when you edit the original files without having to re-link. If you change the set of files being linked by adding to `install.conf.yaml`, then you should re-run `install.sh`.

**Comment by dietofworms** [comment]
Okay great. Let's say I have another config file which I did not add during the initial setup. Am I correct in assuming this is the process to add that into the dotfiles system:
- Copy file(s) to `./dotfiles` and verify they copies over correctly;
- Delete the original files;
- Run `install.sh`

**Comment by anishathalye** [comment]
Before step 3, you also need to modify your `install.conf.yaml` to add the new file.

**Comment by dietofworms** [comment]
Okay thanks. I am going to close this issue.
