### ISSUE TITLE
source command in shell script to reload .bashrc not executing

### ISSUE THREAD

**Issue by hwamil** [anishathalye/dotbot#237]
```
shell:
  - . $HOME/.bashrc
  - source $HOME/.bashrc

```
Both lines do not reload the new .bashrc.
I also can't seem to use export PATH in the shell section (nor does it work in 'install').

But if I run

```
shell:
  - bash

```
It loads the new .bashrc (I confirmed this by appending 'neofetch' to the .bashrc), but when it runs the subsequent commands the shell is back to the old configuration.

I want to be able to reload the .bashrc or execute the rest of the commands in a new shell so that the process can become even more hands off.

On that note, I also have a command that gives me options (installing Rust) - is there a way to automatically choose the default option and execute the installation?

Thank you in advance!

**Comment by anishathalye** [comment]
Dotbot runs each shell command in an independent shell. So e.g. that first command is spawning a shell, having it source your bashrc, and then the shell is exiting, which is not very useful.

If you want to reload your bashrc in your current shell, there's no way you can do that in the `install.conf.yaml` itself. You can add a `source bashrc` to your `./install` bash script, but even then, you won't be able to run it as `./install`, because that spawns the install script in a separate process as well, you'd need to `source install` (which is not recommended).

I'd suggest not doing this and instead doing something like `./install && exec bash` to restart your current shell (which will load the new bashrc).

If you have a command that gives you options, check if it supports a non-interactive mode of operation where those options are given as command-line flags instead of inputs over stdin. Dotbot does not support supplying special input over stdin; you may be able to do something like this using [expect](https://linux.die.net/man/1/expect).
