### ISSUE TITLE
~/.config/Code/User already exists but is a regular file or directory

### ISSUE THREAD

**Issue by adelerhof** [anishathalye/dotbot#241]
I would like to place my VSCode settings.json in the standard directory ~/.config/Code/User, but I can't delete the whole directory structure, there's standard data in subdir's like:
```
~/.config/Code/User/globalStorage
~/.config/Code/User/snippets
```

How do I prevent the error below in this case?

~/.config/Code/User already exists but is a regular file or directory

My settings are:

```
- link:
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.config/Code/User:
      create: true
```

**Comment by anishathalye** [comment]
Yeah, you can't link `User` because that directory exists already (and contains stuff you don't want to track in your dotfiles). In that case, you can specifically link the individual file you are interested in linking. Here's an example where I've done something similar with specific IPython-related files (rather than linking a whole dir): https://github.com/anishathalye/dotfiles/blob/63131479f69634843989ac1e07e9ee94b9f21935/.install.conf.yaml#L24-L26

**Comment by adelerhof** [comment]
Works like a charm, for others, both formats work:
```
    ~/.config/Code/User/settings.json: config/vscode/settings.json
# or
    ~/.config/Code/User/settings.json:
      create: true
      path: config/vscode/settings.json
```

@anishathalye , Thanks a lot!
