### ISSUE TITLE
Does this supports Windows 8

### ISSUE THREAD

**Issue by shivapoudel** [anishathalye/dotbot#25]
@anishathalye Is this dotbot compatiable with windows 8 or not. If compatiable can you link the example repo.

![capture](https://cloud.githubusercontent.com/assets/3774827/7229339/4c9c5468-e782-11e4-9e88-934f2febcc4f.PNG)

Project: https://github.com/shivapoudel/dotfiles

**Comment by anishathalye** [comment]
I've tested Dotbot on Linux and Mac OS, but I haven't tried using it on Windows. I think the symlinking functionality might not work quite right (does NTFS have symbolic links?).

I think some people have tried porting Dotbot to Windows. See [Eric Subach's repo](https://github.com/ericsubach/dotbot) for more details.

**Comment by shivapoudel** [comment]
Right now I can create symbolic link using this command:
```bash
ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig
```

**Comment by anishathalye** [comment]
Hmm, so that must be using some MINGW-supplied `ln`...

Dotbot uses Python's `os.symlink` to make links. You may be able to (fairly painlessly) make it work on Windows by forking Dotbot and editing [linker.py](https://github.com/anishathalye/dotbot/blob/bdc1b2205f00c7fb80412668edb1171155b3fcec/dotbot/executor/linker.py).

**Comment by shivapoudel** [comment]
Ref: #137 and this is solved with this wiki https://github.com/anishathalye/dotbot/wiki/Troubleshooting
