### ISSUE TITLE
Use GitHub's release management

### ISSUE THREAD

**Issue by carlsmedstad** [anishathalye/dotbot#273]
Hey and thanks for a great piece of software :wave: 

Would it be possible for this project to start using the GitHub's [releases management feature](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository)? As far as I'm aware it's not possible to get notified on new tags in a repository, but for _Releases_ it is. Additionally, it creates a neat little _Releases_ section in the side-bar.

**Comment by anishathalye** [comment]
Sure, I'd be happy to do that if it would be helpful. I think I had un-checked the box to show releases in the sidebar; I just re-enabled it. Is that sufficient? E.g. this exists now: https://github.com/anishathalye/dotbot/releases/tag/v1.19.0, because that tag exists. Or do I need to manually publish a new release every time I push a tag for people to get notified?

**Comment by carlsmedstad** [comment]
I see! Since released tags seem to turn up under _Releases_ I think notifications should work as expected. I did not know it was possible to hide that menu so I assumed the feature was disabled completely. I'll be sure to test the https://github.com/user/project/releases URL next time I have this question.

Thank you for the quick reply!
