### ISSUE TITLE
Streamline readme

### ISSUE THREAD

**Issue by joshblum** [anishathalye/dotbot#28]
As a new user I found the README seemed like it was written upside down. I wanted a full example first and I could guess at what most of the syntax meant and then a full explanation when I wanted to customize a bit more. I think the README could be reorganized, streamlining the integration process. I have a few more detailed ideas and can submit a PR with my copy edits. Thoughts?

**Comment by anishathalye** [comment]
That sounds like a great idea.

Maybe we can keep the intro paragraph, the have the setup section, then configuration, full example, and put all the details last. The in-depth examples of each type of command are probably unnecessary for people who can infer how they work by looking at the full example, so that stuff can go further down in the document. And I guess the dotfiles organization and template section could probably go lower down as well. Or something like that...

Did you have something similar in mind? It would be awesome if you could submit a PR.

**Comment by joshblum** [comment]
I'll submit a PR with what I had in mind and then we can work on it together. Do you prefer submitting the PR here or to the dotbot-dev repo?

**Comment by anishathalye** [comment]
You can submit a PR here. The dotbot-dev repo is for me to be able to have feature branches that don't show up on everyone's computers (because Dotbot is usually used as a submodule...).

**Comment by joshblum** [comment]
closed by #29
