### ISSUE TITLE
Replace with backup

### ISSUE THREAD

**Issue by warang580** [anishathalye/dotbot#36]
As I used Dotbot to create my dotfiles repository, I have seen other tools that allows to replace current "real" files by the new symlink and putting them in a `backup` folder instead of doing nothing is there is already a file. That would be really useful, as I had to it myself manually.

It could be something like :

`$ ./install --replace`

If you implement it, in the `dotfiles_template` repository you could add a `backup` folder with its content gitignored.

**Comment by anishathalye** [comment]
This was discussed before in #12.

I think this might be a good thing to include in Dotbot 2.0. I don't think it's a huge pain point for now, because it's a one-time thing when deploying to a new system. For updates, it shouldn't come up.

I agree that it's a nice feature to have, and perhaps default options (#34) might be the best way to implement this. You could have something like:

```yaml
default:
  link:
    backup: ./backup
    replace: true
```
