### ISSUE TITLE
dotfiles directory in the config?

### ISSUE THREAD

**Issue by Brottweiler** [anishathalye/dotbot#50]
I am finally going to put my dotfiles on a git repo, mostly because of backups. I was gonna use your tool for it!

The first question is about the config, though. In the example config, and in other configs I've seen, there's this line:

```
- link:
    ~/.dotfiles: ''
```

This causes this output (removed useless lines):
```
~/.dotfiles already exists but is a regular file or directory
Some links were not successfully set up
==> Some tasks were not executed successfully
```

Can you explain this? I don't really get it.

**Comment by anishathalye** [comment]
I've done that in my config because I keep my dotfiles directory in some other location (`~/.../Anish/src/dotfiles`), but then I want a symlink in a known location so I can reference it from [other places](https://github.com/anishathalye/dotfiles/blob/faeade8372e46d30484c2a56cae0ee745a8eb211/zsh/aliases.zsh#L20).

If you're already keeping your dotfiles in `~/.dotfiles` or you don't need the link to your dotfiles, then you can go ahead and remove that line.

**Comment by Brottweiler** [comment]
Ah alright, I had my dotfiles in `~/dotfiles` first but noticing that line in the config I moved it. 

That's good to know, thanks!
