### ISSUE TITLE
JSON config files are being parsed as YAML

### ISSUE THREAD

**Issue by casey** [anishathalye/dotbot#63]
I started looking at the 491 dotbot configs I pulled, and I noticed that 6 of them failed to parse. 5 were the kinds of things you would expect, mostly due to the ":" character inside of bare strings, which YAML doesn't like.

One was kind of interesting though, it's from this config file: https://github.com/adambubenicek/dotfiles/blob/master/install.conf.json

The problem is that it looks like he's using tabs for indentation, and YAML doesn't allow tabs. This is pretty much the only significant way that the JSON subset of YAML differs from JSON proper.

It might be good to call out this one difference in the readme, since the readme says that JSON config files are allowed, which isn't 100% accurate, since they're still parsed as YAML. Another option would be to explicitly use a JSON parser for '.json' config files.

**Comment by anishathalye** [comment]
Nice to see that you ended up analyzing the configs!

Whoa, I didn't know that JSON wasn't actually a subset of YAML. Even though the tabs issue is pretty minor, you're right, we should do something about it.

What do you think is better? I'm leaning towards adding a note to the readme. I don't think way too many people want to use tabs in their config file anyways. And also, YAML is the recommended format to use (because it looks cleaner).

**Comment by casey** [comment]
Yeah, I think I think that calling it out in the readme is a good idea. I found that people actually use a ton of different names for their config files, so trying to do anything clever based on the filename is probably a brittle approach.

**Comment by anishathalye** [comment]
Ok, I agree with you that filename based stuff is not a good idea.

I can add this to the readme once I get a chance. By the way, do you know if there are any other differences or gotchas?

**Comment by casey** [comment]
Sounds good!

Nope, I googled a bit and I didn't find any other gotchas.

**Comment by anishathalye** [comment]
Cool, thanks for the information Casey!

I've made a change to the readme to add this information (see https://github.com/anishathalye/dotbot/commit/57265f78b4e4f6ca67393f55b2b08f6f45a02ff1). Credits in the commit message.

**Comment by bchretien** [comment]
Wouldn't it be better if JSON files were parsed as JSON? Saying that JSON is supported, but parsing it as YAML is misleading. Plus, JSON support is [part of the standard library](https://docs.python.org/2/library/json.html).

**Comment by anishathalye** [comment]
You're right, it is slightly misleading, and it's weird that we don't parse JSON with the built-in JSON parsing library. 

However, as Casey pointed out, relying on looking at the filename to decide whether to parse as JSON is hard, because people do all sorts of weird things with the filename. Are there any better ways of doing it? For the majority of people, the YAML parser works fine, even with JSON. Guessing the file type incorrectly (as JSON instead of YAML) is something that needs to be avoided, because it could break existing installs. A different way to do it is using try/catch, using the YAML parser first and then trying the JSON parser if that doesn't work.

There are a couple good reasons for keeping things the way they are and parsing everything as YAML:

* We've been parsing JSON as YAML for the past year already.
* I thought YAML was supposed to be a true superset of JSON, and it looks like it basically is, with the exception of not supporting tabs.
* Most people use YAML anyways, and that is the recommended file format.

Arguments against leaving it the way it is:

* Anybody who is using an older version of Dotbot with a JSON file with tabs present will have their configuration break if they upgrade to the latest version of Dotbot.

**Comment by bchretien** [comment]
I actually advertised dotbot to friends, and one of them quickly complained about that JSON issue and just stopped right there (I guess he used tabs as well). I told him to report the issue (he didn't), and to use YAML which feels like a far better format for that kind of manual configuration files anyway. Still, if something goes wrong the first time you use a system that will handle your dotfiles or any other sensitive data, you may want to look elsewhere (I probably would), which is a shame since dotbot works flawlessly for YAML aficionados :-)

Using the JSON parser if (and only if) the file extension is `json` would make sense. This would solve these corner cases without breaking compatibility or adding new dependencies. As you pointed out, they did their best to make YAML a superset of JSON, I actually thought there were more differences than that, but I guess most of the issues were solved in the [1.2 revision of the spec](http://yaml.org/spec/1.2/spec.html), and only the lack of tab support will remain. Now if people use JSON with tabs and without the filename extension, only the try/catch approach would work I guess.

**Comment by anishathalye** [comment]
Gah. Okay, I'm sold :stuck_out_tongue:

I'm thinking of going with the try/catch option because it seems slightly more robust and more Pythonic (ask for forgiveness instead of permission).

**Comment by anishathalye** [comment]
Okay, fixed in c48d16c, tested with Python 2 and Python 3!

I'm travelling right now, so the commit will be tagged and signed once I get back and have access to my signing key again.

**Comment by casey** [comment]
After thinking about it, I'm definitely in agreement that allowing users to write their config files in JSON is a good thing. I use spaces instead of tabs in my editor, and I already know YAML, but for someone who has to configure their editor specially and learn a new and admittedly quite elaborate language, being able to use JSON is great.

But I'm not sure that trying YAML, falling back to JSON, and then surfacing the YAML exception either way is the right way to go. A tab-using user who has a malformed JSON config file will always get an error message about tabs, instead of the actual JSON error which would help them fix their config.

I think maybe the filename option may actually be the best.

**Comment by anishathalye** [comment]
Yeah, you're right. Fixed in 47ad7f4d.
