### ISSUE TITLE
Directive Plugins

### ISSUE THREAD

**Issue by casey** [anishathalye/dotbot#65]
A great way to extend the functionality of dotbot would be to allow user-written plugins. These would allow custom directives alongside `link`, `clean`, and `shell`. I thought of this while looking at what people were doing with dotbot in casey/dotbot-user-study. I had written a `dir` directive, and csivanich/dotbot adds a new `meta` directive. The meta directive is used to print headers which separate logically grouped sections of directives.

Adding functionality to support directive plugins would allow users to extend dotbot without maintaining a fork. (Which I and csivanich both currently do.)

They could maintain the plugins in their dotfile repos, or in separate repos which could be pulled in as submodules and used by several dotfile repos.

Probably more users would write custom directives with a clear framework in place to do so, and it's likely that some of these would be interesting or useful enough to be included in dotbot proper, or possibly in a "contrib" folder of the repo.

I think the implementation would be pretty easy, since python allows for dynamically loaded modules.

A good interface would be to allow users to modify their `install` script and add `--plugin=path/to/plugin.py` flags to the invocation of dotbot. Dotbot could then load these modules at runtime and allow them to register new directive names.

What do you think? I'd be happy to write a PR.

**Comment by casey** [comment]
Oh yeah, I also found another kind of custom directives. I forgot where I found it, but someone had a directive called 'aliases', which didn't do anything, but which contained chunks of yaml which were reused in other parts of the config files, usingt the yaml anchor/alias features, `&name` to introduce for a substructure, and '*name' to use it later. It isn't exactly a directive per-se, but having a directive which was simply ignored would allow users to introduce these kinds of extra data items and reuse them elsewhere.

**Comment by bchretien** [comment]
@casey you may be referring to [my dotfiles](https://github.com/bchretien/dotfiles/blob/master/install.conf.yaml#L1-L18). I often use that YAML feature to prevent copy/pasting parts of YAML files (especially if I plan on modifying these values manually), but for dotbot configuration files I doubt this particular use case exists (paths are different). Here I used that since it made the file clearer as I often had to comment these blocks to enable vim and/or neovim support. Now if I need to add some other "complex" tasks, they'll probably end up in that aliases section as well.

**Comment by anishathalye** [comment]
Awesome idea. I'm totally on board. I added this as (the first!) accepted feature for Dotbot 2.0 (see #35).

I agree with basically everything you said. We'll need to figure out exactly how the API for this will look, which might be somewhat tricky, especially because we might want to make a bunch of other changes in Dotbot 2.0.

One other random point: would it be better to specify a `--plugin=path/to/plugin.py` or better to have a `--plugin-dir=path/to/dir/` and load (possibly multiple) plugins from there?

**Comment by casey** [comment]
Sweet!

What do you think about adding this before 2.0? Because it lives behind a flag, it will be a backwards compatible change.

Re: file vs directory, I think file is the way to go. Argparse supports `action="append"`, which allows the same flag to be given multiple times, so users can still use multiple plugins. Also, we might like to eventually supply a directory of additional plugins in the main repo. Letting users specify individual files would let them pick and choose which they wanted to use.

**Comment by anishathalye** [comment]
I'm okay with adding this to 1.0.

I just want to make sure that this feature will translate naturally to v2.0 -- we don't want to have to redesign the API and break plugins written for 1.0 (even though that's totally legal with a backwards-incompatible change).

Re: file vs directory: why not both? Support both `--plugin-dir` and `--plugin`, so people can use a directory if they don't need to individually select plugins, but they can select individual ones if necessary.

**Comment by casey** [comment]
Alright, check out [dotbot test](https://github.com/casey/dotbot-test). It is an example of how plugins might work. It contains [casey/dotbot](https://github.com/casey/dotbot/tree/directive-plugins) as a submodule, pointing to the "directive-plugins" branch, which is a simple implementation of plugins.

I think that the way to load modules from files is different in different python versions, at least according to [this stackoverflow post](http://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path). Before submitting an actual pull request, I'll make the changes necessary to get it working with earlier python versions.

What do you think of the implementation? I'm more than happy to make changes before submitting a pr. Also, do you have any thoughts about things that should be done differently to be compatible with 2.0?

I was thinking that it might be nice to take the existing plugins, `clean`, `link`, and `shell`, and turn them into loadable plugins which are just loaded by default. Basically the only change will be that they'll load stuff from dotbot explicitly as `import dotbot` instead of `import .`. Also, this would mean that the mechanism for loading plugins would always be tested, since it would always be in use, even in the default configuration.

I think `--plugin-dir` might be more trouble than it's worth. I think people are only likely to load one or two plugins, so specifying them on the command line won't be too much of a bother. But, I don't feel super strongly about this, so if you want `--plugin-dir` I'll be happy to add it.

**Comment by anishathalye** [comment]
Cool, this looks like a good start.

Yeah, looking at that StackOverflow post, it looks like we might have to have different code depending on Python version for plugin loading. I don't think that's a big deal though.

I don't know what 2.0 will look like, so it's hard to say for sure. (worst case, we don't make plugins backwards compatible). One thing that I can think of is default options (e.g. with link, set relink to true). It might be good to add default options to 1.x and finalize the API in terms of the Executors.

I like your idea of having `clean`, `link`, and `shell` be loadable plugins.

Hmm, yeah, idk about `--plugin-dir`. We could leave it out for now and add it later if there's a need for it.

By the way, I don't think too many people will write their _own_ plugins, but I think many people will want to use plugins written by others. Certain people might want to distribute their plugins in a way such that it's easy for others to use them. Just distributing source files isn't great because keeping stuff updated is a pain. If we can handle plugins in a way similar to how [pathogen](https://github.com/tpope/vim-pathogen) does it (see example use [here](https://github.com/anishathalye/dotfiles/tree/master/vim/bundle)), then a nice workflow could be to add all your 3rd party plugins as submodules alongside the custom ones, and then keeping stuff up-to-date is much easier.

**Comment by casey** [comment]
What versions of python is dotbot compatible with? I see that the tests use a stock ubuntu/trusty64 vm. How is python3 vs python2 tested? Since there are 3 different ways of loading modules, depending on the version of python, I want to make sure that the tests cover all of them.

I think that having plugins as submodules should be the recommended way to use and distribute them. With the current install script though, users with plugins in a submodule would have to run `git submodule --update` after cloning before running the install script, otherwise the plugins wouldn't be present.

One possible fix would be to change the install script to run `git submodule update --update --recursive` without `${DOTBOT_DIR}` as an argument, so that all submodules are updated, not just the dotbot submodule. This is already very commonly done, in face something like 312 of the ~500 configs I looked at had `git submodule update` as a `shell` command. Is there a reason that running `git submodule update` in the install script might break stuff, or cause unwanted side effects?

**Comment by anishathalye** [comment]
Python 2.7+. You can see the versions we test against by looking at `.travis.yml`. So don't worry too much about that.

There is one possible unintended side effect of updating all the sub modules for somebody - if someone has gone into a sub module and manually checked out a specific revision, running this will switch to whatever revision has been committed. And I think it'll fail if a user has a dirty sub module somewhere (even if it's not Dotbot related).

There's another way to do it -- the user can give a `plugin` directory as an argument in addition to `$DOTBOT_DIR`. This will update only what we need to. And it's a one-time change for the user, which is nice.

**Comment by anishathalye** [comment]
There's another way to do it -- the user can give a `plugin` directory as an argument in addition to `$DOTBOT_DIR`. This will update only what we need to. And it's a one-time change for the user, which is nice.

**Comment by anishathalye** [comment]
Fixed by #71.
